const CFG=window.DURGA_CONFIG||{};
let current=0;const slides=[...document.querySelectorAll('.slide')],dots=[...document.querySelectorAll('.dot')];
function showSlide(i){current=(i+slides.length)%slides.length;slides.forEach((s,n)=>s.classList.toggle('active',n===current));dots.forEach((d,n)=>d.classList.toggle('active',n===current));}
document.querySelector('.next').onclick=()=>showSlide(current+1);document.querySelector('.prev').onclick=()=>showSlide(current-1);dots.forEach(d=>d.onclick=()=>showSlide(+d.dataset.i));setInterval(()=>showSlide(current+1),7000);
const phone=document.getElementById('footerPhone'),email=document.getElementById('footerEmail');if(phone&&CFG.CONTACT_PHONE_1)phone.textContent=CFG.CONTACT_PHONE_1+(CFG.CONTACT_PHONE_2?' | '+CFG.CONTACT_PHONE_2:'');if(email&&CFG.CONTACT_EMAIL)email.textContent=CFG.CONTACT_EMAIL;
const demo=!CFG.SUPABASE_URL||CFG.SUPABASE_URL.includes('YOUR_PROJECT')||CFG.DEMO_MODE;
let supabaseClient=null;
async function loadSupabase(){if(supabaseClient||demo)return;const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';document.head.appendChild(s);await new Promise(r=>s.onload=r);supabaseClient=window.supabase.createClient(CFG.SUPABASE_URL,CFG.SUPABASE_PUBLISHABLE_KEY)}
const fmt=n=>'₹'+Number(n||0).toLocaleString('en-IN');
function years(){const y=new Date().getFullYear();const el=document.getElementById('yearFilter');for(let i=y;i>=y-5;i--){const o=document.createElement('option');o.value=i;o.textContent=i;el.appendChild(o)}}years();
async function loadLedger(){const rows=document.getElementById('donationRows');if(demo){document.getElementById('totalIncome').textContent='₹0';document.getElementById('totalExpense').textContent='₹0';document.getElementById('balance').textContent='₹0';rows.innerHTML='<tr><td colspan="4">Backend जोड़ने के बाद वास्तविक सार्वजनिक चंदा रिकॉर्ड यहाँ दिखेगा।</td></tr>';return}await loadSupabase();const year=+document.getElementById('yearFilter').value,month=document.getElementById('monthFilter').value;let q=supabaseClient.from('public_ledger').select('*').gte('paid_at',`${year}-01-01T00:00:00`).lt('paid_at',`${year+1}-01-01T00:00:00`).order('paid_at',{ascending:false});const {data,error}=await q;if(error){rows.innerHTML=`<tr><td colspan="4">रिकॉर्ड नहीं मिल सके।</td></tr>`;return}const filtered=month==='all'?data:data.filter(x=>new Date(x.paid_at).getMonth()+1===+month);let income=filtered.reduce((s,x)=>s+Number(x.amount),0);let eq=supabaseClient.from('public_expenses').select('amount,spent_at').gte('spent_at',`${year}-01-01T00:00:00`).lt('spent_at',`${year+1}-01-01T00:00:00`);const er=await eq;let expenses=(er.data||[]).filter(x=>month==='all'||new Date(x.spent_at).getMonth()+1===+month).reduce((s,x)=>s+Number(x.amount),0);document.getElementById('totalIncome').textContent=fmt(income);document.getElementById('totalExpense').textContent=fmt(expenses);document.getElementById('balance').textContent=fmt(income-expenses);rows.innerHTML=filtered.length?filtered.map(x=>`<tr><td>${escapeHtml(x.donor_name)}</td><td>${fmt(x.amount)}</td><td>${new Date(x.paid_at).toLocaleString('hi-IN')}</td><td><a href="receipt.html?receipt=${encodeURIComponent(x.receipt_no)}">${escapeHtml(x.receipt_no)}</a></td></tr>`).join(''):'<tr><td colspan="4">इस अवधि में कोई भुगतान रिकॉर्ड नहीं है।</td></tr>'}
function escapeHtml(s){return String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
document.getElementById('refreshLedger').onclick=loadLedger;loadLedger();
document.getElementById('donationForm').addEventListener('submit',async e=>{e.preventDefault();const status=document.getElementById('paymentStatus');const name=document.getElementById('donorName').value.trim(),phonev=document.getElementById('donorPhone').value.trim(),amount=Number(document.getElementById('donationAmount').value);if(!/^[0-9]{10}$/.test(phonev)){status.textContent='कृपया सही 10 अंकों का मोबाइल नंबर डालें।';return}if(amount<1){status.textContent='कृपया सही राशि डालें।';return}if(demo){status.textContent='Payment अभी demo mode में है। config.js में Supabase और Razorpay keys जोड़ने के बाद online payment चालू होगा।';return}await loadSupabase();status.textContent='Payment तैयार किया जा रहा है…';const {data,error}=await supabaseClient.functions.invoke('create-order',{body:{name,phone:phonev,amount}});if(error||!data?.order_id){status.textContent='Payment order नहीं बन सका।';return}const rzp=new Razorpay({key:CFG.RAZORPAY_KEY_ID,amount:data.amount,currency:'INR',name:'श्री श्री दुर्गा पूजा महोत्सव',description:'छात्र नवयुवक संघ, तिलोखर (रोहतास)',order_id:data.order_id,prefill:{name,contact:phonev},theme:{color:'#8f0c10'},handler:async response=>{status.textContent='Payment verify हो रहा है…';const v=await supabaseClient.functions.invoke('verify-payment',{body:response});if(v.error){status.textContent='Payment verify नहीं हो सका।';return}window.location.href='receipt.html?receipt='+encodeURIComponent(v.data.receipt_no)}});rzp.open()});
